server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vue_test_demo?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: qwer1234
    diver-class-name: com.mysql.cj.jdbc.Driver
#  mvc:
#    static-path-pattern: /static/**
